import Head from "next/head";
import { useEffect, useRef, useState } from "react";

import { Quiz } from "../components/Quiz";
import AnswerModel from "../models/answer";
import QuestionModel from "../models/question";

import styles from "../styles/Home.module.scss";

const questionTest = new QuestionModel(1, "Qual é a melhor cor?", [
  AnswerModel.isWrong("Verde"),
  AnswerModel.isWrong("Vermelha"),
  AnswerModel.isWrong("Azul"),
  AnswerModel.isCorrect("Preta"),
]);

const BASE_URL = "http://localhost:3000/api";

export default function Home() {
  const [question, setQuestion] = useState<QuestionModel>(questionTest);
  const [questionIds, setQuestionIds] = useState<number[]>([]);
  const questionRef = useRef<QuestionModel>();

  async function loadQuestionIds() {
    const response = await fetch(`${BASE_URL}/quiz`);
    const questionIds = await response.json();
    console.log("🚀 ~ questionIds", questionIds);

    setQuestionIds(questionIds);
  }

  async function loadQuestion(questionId: number) {
    const response = await fetch(`${BASE_URL}/questions/${questionId}`);
    const questionJSON = await response.json();
    console.log("🚀 ~ questionJSON", questionJSON);
  }

  useEffect(() => {
    loadQuestionIds();
    // questionRef.current = question;
  }, []);

  useEffect(() => {
    if (questionIds.length > 0) {
      loadQuestion(questionIds[0]);
    }
  }, [questionIds]);

  function handleAnsweredQuestion(question: QuestionModel) {}

  function handleNextQuestion() {}

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Quiz | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Quiz
        question={question}
        lastQuestion={true}
        handleAnsweredQuestion={handleAnsweredQuestion}
        handleNextQuestion={handleNextQuestion}
      />
    </div>
  );
}
